#!/usr/bin/perl
use strict;
use warnings;

use Data::Dumper;
do '../bin/setlib.cfg';
require Foswiki;
new Foswiki('admin');

require Foswiki::Plugins::AppManagerPlugin;

if(@ARGV < 1){
	printHelp();
	exit;
}

my $command = $ARGV[0];

if($command eq 'install'){
	install();
	exit;
}
elsif($command eq 'list'){
	list();
	exit;
}
elsif($command eq 'uninstall'){
	uninstall();
	exit;
}

sub printHelp{
	print "Usage: appmanager <command> [params...]\n";
	print "\n";
	print "Available commands:\n";
	print "install\n";
	print "\tExample: appmanager install MinutesAppContrib default\n"
}

sub install{
	my $appName = $ARGV[1];
	my $installName = $ARGV[2];

	unless($installName){
		$installName = "default";
	}
	unless($appName){
		print "For installation please specify the app name\n";
		exit;
	}

	if($appName eq 'all'){
		Foswiki::Plugins::AppManagerPlugin::_installAllNew();
		exit;
	}

	my $appList = Foswiki::Plugins::AppManagerPlugin::_applistnew();
	my $appToInstall;
	foreach my $app (@$appList){
		if($app->{name} eq $appName){
			$appToInstall = $app;
		}
	}
	if(!$appToInstall){
		print("No app configuration found for app $appName\n");
		exit;
	}
	my $appDetails = Foswiki::Plugins::AppManagerPlugin::_appdetailnew($appToInstall->{id});
	foreach my $installConfig (@{$appDetails->{appConfig}->{installConfigs}}){
		if($installConfig->{name} eq $installName){
			my $installResult = Foswiki::Plugins::AppManagerPlugin::_installNew($appName, $installConfig);
			if($installResult->{success} eq "false"){
				print "Installation failed: ";
				print $installResult->{message}."\n";
			}
			else{
				print "Installation finished\n";
			}
			exit;
		}
	}
	print "No install configuration found for $installName\n";
	exit;
}

sub list{
	my $appList = Foswiki::Plugins::AppManagerPlugin::_applistnew();
	print "Apps managed by the AppManager:\n";
	foreach my $app (@$appList){
		print "\t".$app->{name}."\n";
		my $history = Foswiki::Plugins::AppManagerPlugin::_readHistory($app->{name});
		if($history->{installed} && ref($history->{installed}) eq "HASH"){
			print "\t\tInstalled in: ";
			print join(",",keys(%{$history->{installed}}))."\n";
		}
		else{
			print "\t\tNot installed\n";
		}
	}
	exit;
}

sub uninstall{
	my $appName = $ARGV[1];
	my $webName = $ARGV[2];

	unless($appName && $webName) {
		print "For uninstallation please specify the app name and the web name\n";
		exit;
	}

	Foswiki::Plugins::AppManagerPlugin::_uninstall($appName, $webName);
	exit;
}